add missing upload form $v.tar.gz.sha512sum
tinkerbell/osie pull request #137
Opened 2020-09-23 17:39 UTC by MaxPeal

## Description

upload latest.tar.gz.sha512sum and $v.tar.gz.sha512sum also to AWS

## Why is this needed

to make it possibly to cache and verify the osie tar locally and skip a not needed new redownload

Fixes: #
slow or corrupt downloads

## How Has This Been Tested?
not tested as on my system its takes a half day!

## How are existing users impacted? What migration steps/scripts do we need?

no impact for existing users.

migration steps after this RP: add the logic for the sha512sum check to
- [ ] tink/setup.sh
- [ ] tink/generate-envrc.sh
- [ ] sandbox/setup.sh
- [ ] sandbox/generate-envrc.sh

2020-09-23 17:56 UTC, mmlb approved these changes

2020-09-23 17:56 UTC, mmlb commented on rules.mk.j2
> +	$(Q) echo
Oops sorry I didn't see this, can you remove this line (squash into this commit) please.

2020-09-23 17:56 UTC, mmlb requested changes
wrong button, meant to req changes

2020-09-28 11:08 UTC, MaxPeal commented
@mmlb done, 
i done also a Merge branch with Mergify

2020-09-28 11:10 UTC, MaxPeal commented
in the continuous-integration/drone/pr  drone i get an error: "Insufficient privileges to use volumes"
mybe a right problem for my user at drone.packet.net?

2020-09-28 16:24 UTC, mmlb approved these changes

2020-09-28 16:28 UTC, merged

2020-09-28 16:29 UTC, mmlb commented
Thanks a lot @MaxPeal!