Do not fail deprovisions when SOL causes docker to hang
tinkerbell/osie pull request #188
Opened 2021-01-29 03:22 UTC by ScottGarman

If SOL isn't working properly during deprovision, docker can hang even
though the deprovision script has run to completion. This change sets
the autofail message to "deprovision completed" at the very end of the
deprovision script, so that if docker hangs and is killed by the timeout
watcher, we can detect that the deprovision script completed and cleanup
gracefully instead of failing the deprovision.

Signed-off-by: Scott Garman <sgarman@packet.com>

2021-01-30 00:17 UTC, markyjackson-taulia approved these changes

2021-01-30 02:45 UTC, mmlb requested changes

2021-01-30 02:45 UTC, mmlb commented on apps/osie-installer.sh
> +			# report failure in that case, but just run the cleanup() function and exit.
docker doesn't actually hang right? docker exits with an error and so the script exits and then this trap is reached and we phone back with a timed out error. I think thats the case at least, if so can you update the comment to match.

2021-01-30 02:45 UTC, mmlb commented on apps/osie-installer.sh
> +			if [ "$stage" = "deprovision completed" ]; then
we shouldn't tie this to just deprovision, how about just handling `stage=completed`?

2021-02-19 20:09 UTC, dlaube commented
> If SOL isn't working properly during deprovision, docker can hang even
> though the deprovision script has run to completion. This change sets
> the autofail message to "deprovision completed" at the very end of the
> deprovision script, so that if docker hangs and is killed by the timeout
> watcher, we can detect that the deprovision script completed and cleanup
> gracefully instead of failing the deprovision.
> 
> Signed-off-by: Scott Garman [sgarman@packet.com](mailto:sgarman@packet.com)

We are seeing this problem on OSIE provisions as well. I have tested this build on a new c3.medium open19 machine in NY5 and the same failure mode is observed. The error received even with this build is "Timed out during OSIE final stage" All other steps appear successful and if we reboot the machine manually, it makes it successfully into the target OS fine.

2021-03-08 19:29 UTC, mmlb commented
I've tweaked this to also work for more than just deprovisions and opened up #198 because I can't push to your branch @ScottGarman :/

2021-03-08 19:29 UTC, closed without merging