apps/workflow-helper: set CAPTURE_ACTION_LOGS to false in tink-worker env
tinkerbell/osie pull request #235
Opened 2021-06-21 13:03 UTC by splaspood

## Description

Adds CAPTURE_ACTION_LOGS=false to the tink-worker env as defined in apps/workflow-helper.sh.    This prevents tink-worker from 'attaching' to the log output of each action container it spawns.   

## Why is this needed

To send all workflow action output to a centralized log repository by way of boots we need to prevent tink-worker from grabbing that log output first.

2021-06-21 13:44 UTC, markyjackson-taulia approved these changes, later dismissed

2021-06-28 14:16 UTC, mmlb requested changes
Needs a more descriptive commit message, code looks fine though.

2021-06-28 15:53 UTC, ScottGarman approved these changes

2021-06-28 16:23 UTC, mmlb approved these changes

2021-06-28 17:06 UTC, merged