Strip biosdevname and net.ifnames flags for Debian 10
tinkerbell/osie pull request #5
Opened 2020-04-10 17:51 UTC by dustinmiller1337

- [x] Changelog updated

2020-04-10 18:16 UTC, mmlb commented
please add "why" info in the commit message.

2020-04-10 18:32 UTC, mmlb commented on CHANGELOG.md
> +## [20.04.10.00] - 2020-04-10
Lets keep unreleased for now, while we figure out how we do release numbers in new world ;)

2020-04-10 18:35 UTC, mmlb requested changes
see comment

2020-04-10 18:49 UTC, dustinmiller1337 commented
Wasn't entirely sure what was being asked but added back in the unreleased section and moved this under it..

2020-04-13 14:27 UTC, mmlb commented
> Wasn't entirely sure what was being asked but added back in the unreleased section and moved this under it..

Yep that was exactly it, :+1:

2020-04-13 14:27 UTC, mmlb approved these changes

2020-04-13 14:33 UTC, merged