Log OSIE failures to tinkerbell using a bash trap function
tinkerbell/osie pull request #99
Opened 2020-08-25 21:11 UTC by ScottGarman

Similar to what we do in osie-runner, this sets up a bash trap
function named autofail() which logs to tinkerbell an error message
based on the `autofail_reason` variable, which we update in various
sections of the script to reflect which code section the failure
occurred.

2020-08-25 21:14 UTC, mikemrm submitted a review, later dismissed
LGTM!

2020-08-26 23:33 UTC, mmlb requested changes

2020-08-26 23:33 UTC, mmlb commented on docker/scripts/osie.sh
> +trap autofail EXIT
change this to `ERR` and you can do away with the `== "SUCCESS"` handling

2020-08-26 23:33 UTC, mmlb commented on docker/scripts/osie.sh
> +autofail_reason='SUCCESS'
can go away with `trap ... ERR`

2020-08-27 02:42 UTC, ScottGarman commented
Changing this to an ERR trap isn't working, I'll research this more tomorrow.

2020-08-27 20:49 UTC, ScottGarman commented
Manny and I discussed the trap on EXIT vs. ERR issue this morning, and I've implemented the solution we came to. This is ready for final review and merge now.

2020-08-27 20:51 UTC, mmlb approved these changes

2020-08-27 20:55 UTC, merged